name: CI
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        include:
          - jobtype: 1
          - jobtype: 2
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: adopt
    - uses: coursier/cache-action@v6
    - if: ${{ matrix.jobtype == 1 }}
      shell: bash
      run: sbt -v "++2.13.8!" library/test
    - if: ${{ matrix.jobtype == 2 }}
      shell: bash
      run: sbt -v "++2.12.15!" scalafmtCheckAll test scripted
    - shell: bash
      run: |
        rm -rf "$HOME/.sbt/scripted/" || true
        rm -rf "$HOME/.ivy2/local" || true
        rm -r $(find $HOME/.sbt/boot -name "*-SNAPSHOT") || true
        find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
        find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
        find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
        find $HOME/.sbt                              -name "*.lock"               -delete || true
